### ISSUE TITLE
Unexpected behaviour of constraint `RequiredFields`

### ISSUE THREAD

**Issue by starrify** [scrapinghub/scrapylib#52]
### How to reproduce the issue

Assuming we have an item defined like this:
```Python
class TestItem(scrapy.item.Item):
    test_field = scrapy.item.Field()
    constraints = [scrapylib.constraints.RequiredFields('test_field')]
```
And then assign value `False` to the field inside our spider code:
```Python
item = TestItem()
item.test_field = False
yield item
```
Make sure `scrapylib.constraints.pipeline.ConstraintsPipeline` is enabled, and the item would be ignored with the following message given:
> Dropped: missing field: test_filed

### Related code

Starting from line 35 of [`scrapylib/constraints/__init__.py`](https://github.com/scrapinghub/scrapylib/blob/59e042662fce492ac43f5a61cc6387dd74c4722c/scrapylib/constraints/__init__.py#L35)
```Python
class RequiredFields(object):
    """Assert that the specified fields are populated and non-empty"""

    def __init__(self, *fields):
        self.fields = fields

    def __call__(self, item):
        for f in self.fields:
            v = item.get(f)
            assert v, "missing field: %s" % f
```

### My opinions

1. As it's name suggests, `RequiredFields` shall care about only the existence of the field (the key), not the value.

2. I'd like to see another constraint `NonEmptyFields` here to ensure the non-emptyness of the values, which also implicitly ensures the existence of the field.

3. `assert v` is bad. `assert v or v is False` looks better but not good enough. I guess something based on `len(v)` would do.

**Comment by darkrho** [comment]
Something like this should work:

```python
# ...
_missing = object()
# ...

    # ...
    for f in self.fields:
        v = item.get(f, _missing)
        assert v is not _missing, "missing field: %s" % f
    
```
