### ISSUE TITLE
Move Crawlera middleware to its own repositoy

### ISSUE THREAD

**Issue by pablohoffman** [scrapinghub/scrapylib#60]
I think we should move Crawlera middleware to its own repository & python package. Thoughts?

**Comment by nyov** [comment]
I would think it makes more sense to rename `scrapinghub/scrapylib` to `scrapinghub/shublib` and create another `scrapy/scrapylib` then move all the "generic" code over there, keeping scrapinghub services together here.

`scrapy/scrapylib` would then be a better place to move generic code from scrapy which might have fit into contrib/contrib_exp before it was dissolved.

**Comment by qrilka** [comment]
@pablohoffman haven't we moved the middleware already or there is something left to do?
@rdowinton what do you think?

**Comment by rdowinton** [comment]
@qrilka I believe this is a duplicate ticket.
