### ISSUE TITLE
Crawlera.py using scrapy.log

### ISSUE THREAD

**Issue by ccdpowell** [scrapinghub/scrapylib#62]
I just upgraded to scrapy 1.0.0rc2 and it appears that Crawlera's most recent version is still using scrapy.log as opposed to python's logging module.

This should be fixed in next version of crawlera.

**Comment by nyov** [comment]
That one is deprecated and going away.
Use `scrapy-crawlera` package (https://github.com/scrapy-plugins/scrapy-crawlera) instead.

**Comment by nyov** [comment]
@dangra (or someone), could the `crawlera-fork` branch here be pruned or does it have historical value?

**Comment by dangra** [comment]
I think it can be killed, but better ask the author: @qrilka

**Comment by dangra** [comment]
hmm.. very outdated. sorry for the noise kirill, I removed it.
