### ISSUE TITLE
MAGIC_FIELDS  does not replace the item attribute in yielded item object

### ISSUE THREAD

**Issue by DharmeshPandav** [scrapinghub/scrapylib#73]
MAGIC_FIELDS is not replacing the item attribute in yielded Item object

it only adds the new attribute if not present but do not repalce the value if that attribute is already set in yielded item

i am not sure if this is desired behavior but i think It should replace if value for that attribute is present in item object otherwise should add it to item

**Comment by nyov** [comment]
Have you configured the `MAGIC_FIELDS_OVERRIDE` setting?

**Comment by redapple** [comment]
@DharmeshPandav , we're deprecating scrapylib altogether so I'm closing this PR.
If you are still bothered by this magicfields issue, can you open it again against https://github.com/scrapy-plugins/scrapy-magicfields ?
Thanks.
