### ISSUE TITLE
Extract DeltaFetch to scrapy-plugins

### ISSUE THREAD

**Issue by redapple** [scrapinghub/scrapylib#74]
See https://github.com/scrapinghub/scrapylib/pull/72#issuecomment-225969154

**Comment by nyov** [comment]
[thanks!](https://github.com/scrapinghub/scrapylib/pull/72#issuecomment-228809197)

> This middleware now lives at https://github.com/scrapy-plugins/scrapy-deltafetch
> 
> Version 1.0.0 is already [on PyPI](https://pypi.python.org/pypi/scrapy-deltafetch)

**Comment by redapple** [comment]
See https://github.com/scrapy-plugins/scrapy-deltafetch/pull/1
